# Generated by Django 5.2.7 on 2025-10-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('light', 'Lumière'), ('sensor', 'Capteur'), ('plug', 'Prise connectée')], max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
