# Generated by Django 5.2.7 on 2025-11-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100, verbose_name='Nazwa systemu')),
                ('mqtt_broker_url', models.CharField(blank=True, max_length=200, verbose_name='Adres brokera MQTT (informacyjnie)')),
                ('description', models.TextField(blank=True, verbose_name='Opis systemu / informacje o projekcie')),
                ('admin_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail administratora')),
            ],
            options={
                'verbose_name': 'Ustawienia systemu',
                'verbose_name_plural': 'Ustawienia systemu',
            },
        ),
    ]
