# Generated by Django 5.2.7 on 2025-11-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis systemu / Informacje o projekcie'),
        ),
    ]
