# Generated by Django 5.2.7 on 2025-11-14 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('light', 'Swiatlo'), ('sensor', 'Czujnik'), ('plug', 'Gniazdko')], max_length=20),
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('toggle', 'Reczna zmiana stanu'), ('rule', 'Automatyczna zmiana stanu przez regule')], max_length=20, verbose_name='Akcja')),
                ('descpription', models.CharField(max_length=255, verbose_name='Opis zdarzenia')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data i godzina zdarzenia')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='devices.device', verbose_name='Urzadzenie')),
            ],
            options={
                'verbose_name': 'Log zdarzenia',
                'verbose_name_plural': 'Logi zdarzen',
                'ordering': ['-created_at'],
            },
        ),
    ]
