# Generated by Django 5.2.7 on 2025-11-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_type_eventlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlog',
            old_name='descpription',
            new_name='description',
        ),
    ]
