# Generated by Django 5.2.7 on 2025-11-16 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_rename_descpription_eventlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa urządzenia'),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.CharField(max_length=100, verbose_name='Pokój'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('light', 'Swiatlo'), ('sensor', 'Czujnik'), ('plug', 'Gniazdko')], max_length=20, verbose_name='Typ urządzenia'),
        ),
        migrations.AlterField(
            model_name='device',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Wartość'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Czas zdarzenia'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device', verbose_name='Czujnik'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Czas pomiaru'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.FloatField(verbose_name='Wartość'),
        ),
    ]
