# Generated by Django 5.2.7 on 2025-11-20 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_name_alter_device_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Urządzenie', 'verbose_name_plural': 'Urządzenia'},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log zdarzenia', 'verbose_name_plural': 'Logi zdarzeń'},
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('light', 'Swiatło'), ('sensor', 'Czujnik'), ('plug', 'Gniazdko')], max_length=20, verbose_name='Typ urządzenia'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(choices=[('toggle', 'Ręczna'), ('rule', 'Automatyczna')], max_length=20, verbose_name='Akcja'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='devices.device', verbose_name='Urządzenie'),
        ),
    ]
