# Generated by Django 5.2.7 on 2025-11-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_options_alter_eventlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log zdarzenia', 'verbose_name_plural': 'Logi zdarzen'},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['timestamp'], 'verbose_name': 'Dane czujnika', 'verbose_name_plural': 'Dane czujników'},
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(choices=[('manual', 'Reczna'), ('auto', 'Automatyczna')], max_length=20, verbose_name='Akcja'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='devices.device', verbose_name='Urzadzenie'),
        ),
    ]
