# Generated by Django 5.2.7 on 2025-10-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200, verbose_name='name')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
