# Generated by Django 5.2.7 on 2025-11-02 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa reguły')),
                ('enabled', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('comparator', models.CharField(choices=[('lt', '<'), ('le', '<='), ('gt', '>'), ('ge', '>='), ('eq', '=='), ('ne', '!=')], default='lt', max_length=2, verbose_name='Porównanie')),
                ('threshold', models.FloatField(verbose_name='Próg')),
                ('action', models.CharField(choices=[('on', 'Włącz'), ('off', 'Wyłącz'), ('toggle', 'Przełącz')], default='on', max_length=6, verbose_name='Akcja')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnie uruchomienie')),
                ('sensor', models.ForeignKey(help_text="Urządzenie typu 'sensor'", on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_sensor', to='devices.device', verbose_name='Czujnik')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_target', to='devices.device', verbose_name='Urządzenie docelowe')),
            ],
        ),
    ]
