# Generated by Django 5.2.7 on 2025-10-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='energy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='joined_date',
            field=models.DateField(null=True),
        ),
    ]
